In [193]:

import numpy as np

from scipy.ndimage import gaussian_filter
import subprocess
from soma import aims

from sulci.registration.spam import spam_register
from soma.aimsalgo import MorphoGreyLevel_S16

import sulci.registration.spam
from sulci.models import distribution_aims
from sulci.registration.spam import (
    SpamRegistration, dilate_spam_mask, move_image_slightly, spam_register)
from soma import aims, aimsalgo

# Global static variables
_AIMS_BINARY_ONE = 32767
_dilation = 1
_threshold = 0
_nb_spam_subjects = 61

# Anatomist

import anatomist.api as ana
from soma.qt_gui.qtThread import QtThreadCall
from soma.qt_gui.qt_backend import Qt
# launching anatomist
a = ana.Anatomist()

# Define functions

In [194]:
def dilate(mask, radius=_dilation):
    """Makes a dilation radius _dilation, in mm
    """
    arr = mask.np
    # Binarization of mask
    arr[arr < 1] = 0
    arr[arr >= 1] = _AIMS_BINARY_ONE
    # Dilates initial volume of 10 mm
    morpho = MorphoGreyLevel_S16()
    dilate = morpho.doDilation(mask, radius)
    arr_dilate = dilate.np
    arr_dilate[arr_dilate >= 1] = 1
    return dilate

In [195]:
def realign_mi_register(spam_vol: aims.Volume_FLOAT, skel_vol: aims.Volume_S16):
    """Realigns skeleton mask to spam
    
    skel_vol is the test aims volume"""
    
    spam_vol = aims.Volume_FLOAT(spam_vol)
    spam_vol.np[:] = spam_vol.np*100
    skel_vol2 = aims.Volume_S16(skel_vol)
    skel_vol = aims.Volume(skel_vol2.getSize(), 'FLOAT')
    skel_vol.copyHeaderFrom(skel_vol2.header())
    skel_vol.np[:] = skel_vol2.np
    
    # Reads skeleton file
    skel_vol.np[:] = (skel_vol.np > 0).astype(np.float32)
    
    # # Makes binarization and dilation on spam
    # mask_result = aims.Volume(spam_vol.getSize(), 'S16')
    # mask_result.copyHeaderFrom(spam_vol.header())
    # mask_result.np[:] = spam_vol.np
    # mask_result[mask_result.np <= _threshold] = 0
    # mask_result.np[:] = dilate(mask_result).np

    # # Masks skeleton data with dilated spam
    # skel_vol.np[mask_result.np <= 0] = 0
    # skel_vol_masked = aims.Volume_FLOAT(skel_vol)
    aims.write(skel_vol, "/tmp/skel_before.nii.gz")
    skel_vol.np[:] = 100*gaussian_filter(skel_vol.np, sigma=2)
    print(np.unique(skel_vol.np))
    aims.write(skel_vol, "/tmp/skel_before_filtered.nii.gz")
    
    # Writes nifti files
    aims.write(spam_vol, "/tmp/spam.nii.gz")
    
    # Makes realignment
    subprocess.check_call("AimsMIRegister -r /tmp/spam.nii.gz  -t /tmp/skel_before_filtered.nii.gz --dir /tmp/transform.trm", shell=True)
    # print(out_tr.np)
    
    # Applies the realignment
    subprocess.check_call("AimsApplyTransform -i /tmp/skel_before.nii.gz -o /tmp/skel_realigned.nii.gz -m /tmp/transform.trm", shell=True)
    
    # loads realigned file:
    after_vol = aims.read("/tmp/skel_realigned.nii.gz")
    
    return after_vol #, skel_vol_masked

In [196]:
def realign_spam_register(spam_vol: aims.Volume_FLOAT, skel_vol: aims.Volume_S16):
    """Realigns skeleton mask to spam
    
    skel_f is a file name of skeleton file"""
        
    spam_vol = aims.Volume_FLOAT(spam_vol)
    skel_vol = aims.Volume_S16(skel_vol)
    
    # # Reads spam and skeleton files
    # skel_vol.np[:] = (skel_vol.np > 0).astype(np.int16)

    # # Makes binarization and dilation on spam
    # mask_result = aims.Volume(spam_vol.getSize(), 'S16')
    # mask_result.copyHeaderFrom(spam_vol.header())
    # mask_result.np[:] = spam_vol.np
    # mask_result[mask_result.np <= _threshold] = 0
    # mask_result.np[:] = dilate(mask_result).np

    # Masks skeleton data with dilated spam
    # skel_vol.np[mask_result.np <= 0] = 0
    aims.write(skel_vol, "/tmp/skel_before.nii.gz")
    
    # # Reads initial spam volume
    # spam_vol.np[:] = spam_vol.np/_nb_spam_subjects
    
    # Makes realignment
    out_tr = spam_register(spam_vol,
                        skel_vol,
                        do_mask=False,
                        eps=1e-5,
                        R_angle_var=np.pi / 8,
                        t_var=10.,
                        verbose=False,
                        in_log=False,
                        calibrate_distrib=30)
    print(out_tr)
    aims.write(out_tr, '/tmp/transform.trm')
    
    # Applies the realignment
    subprocess.check_call(f"AimsApplyTransform -i /tmp/skel_before.nii.gz -o /tmp/skel_realigned.nii.gz -m /tmp/transform.trm", shell=True)
    
    # loads realigned file:
    after = aims.read("/tmp/skel_realigned.nii.gz")
    
    return after

# Toy model

In [197]:
hdr = dict(aims.StandardReferentials.icbm2009cTemplateHeader())
dims = (np.ceil(np.array(hdr['volume_dimension']) / 2)).astype(int)
vs = np.array(hdr['voxel_size']) * 2
hdr['voxel_size'] = vs

skel_vol = aims.Volume(list(dims), dtype='S16')
skel_vol.copyHeaderFrom(hdr)
skel_vol.fill(0)
skel_vol[60, 10:100, 50] = 1
skel_vol[30, 30:70, 50] = 1 

spam_vol = aims.Volume(list(dims), dtype='FLOAT')
spam_vol.copyHeaderFrom(hdr)
spam_vol.fill(0)
spam_vol[:] = skel_vol[:]

g = aimsalgo.Gaussian3DSmoothing_FLOAT(10., 10., 10.)
spam_vol = g.doit(spam_vol)
spam_vol[spam_vol.np < 0] = 0.

spam_vol.np[:] = spam_vol.np
spam_vol.np[:] = spam_vol.np / spam_vol.max()
aims.write(spam_vol, '/tmp/spam_art.nii.gz')
mc = aims.MassCenters_FLOAT(spam_vol)
mc.doit()
gravity_center = np.expand_dims(np.array(mc.infos()['0'][0][0]), axis=1)

skel_vol[30, 30:70, 50] = 0
skel_vol[25, 25:65, 50] = 1 
skel_vol[60, 10:100, 50] = 0
skel_vol[55, 5:95, 50] = 1


moved_skel, tr = move_image_slightly(skel_vol, (0, 0, 1), np.pi / 20 * 1.5,
                                     np.array((-1.2, 2.3, -3.5)) * 2,
                                     gravity_center)

  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 %

In [198]:
np.unique(moved_skel.np)

array([0, 1], dtype=int16)

In [199]:
np.max(spam_vol.np)

1.0

In [200]:
moved_skel.header()

{ 'referentials' : [ 'Talairach-MNI template-SPM' ], 'transformations' : [ [ -1, 0, 0, 96, 0, -1, 0, 96, 0, 0, -1, 114, 0, 0, 0, 1 ] ], 'voxel_size' : [ 2, 2, 2, 2 ], 'volume_dimension' : [ 97, 115, 97, 1 ], 'sizeX' : 97, 'sizeY' : 115, 'sizeZ' : 97, 'sizeT' : 1, 'referential' : '84b1989b-eb68-8665-0049-8feaf3c22679' }

In [201]:
gravity_center

array([[101.53093719],
       [105.94753265],
       [ 99.98976898]])

In [202]:
print(np.unique(spam_vol, return_counts=True))
print(np.unique(moved_skel, return_counts=True))

(array([0.0000000e+00, 2.0693223e-17, 2.0755027e-17, ..., 9.9996245e-01,
       9.9999940e-01, 1.0000000e+00], dtype=float32), array([544664,      1,      1, ...,      1,      1,      1]))
(array([0, 1], dtype=int16), array([1081905,     130]))


In [203]:
sulci.registration.spam.__file__

'/casa/host/build/python/sulci/registration/spam.py'

In [204]:
after_vol_spam = realign_spam_register(spam_vol, moved_skel)
np.unique(after_vol_spam.np)

[[ 9.7266006e-01  2.3223346e-01  4.5086654e-09 -9.6037903e+00]
 [-2.3223346e-01  9.7266006e-01  3.8295621e-08  2.9355675e+01]
 [ 4.5081259e-09 -3.8295685e-08  1.0000000e+00  8.1126099e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]


/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


loading direct transformations
Output dimensions: 97, 115, 97
Output voxel size: 2, 2, 2 mm
Resampling carto_volume of S16...   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 %


array([0, 1], dtype=int16)

In [205]:
# after_vol_mi = realign_mi_register(spam_vol, moved_skel)
# np.unique(after_vol_mi.np)

In [206]:
skel_a = a.toAObject(moved_skel)
spam_a = a.toAObject(spam_vol)
after_spam_a = a.toAObject(after_vol_spam)
# after_mi_a = a.toAObject(after_vol_mi)
skel_a.setPalette("BLUE-lfusion")
after_spam_a.setPalette("RED-lfusion")
# after_mi_a.setPalette("VIOLET-lfusion")
w = a.createWindow('Coronal')
w.addObjects(spam_a)
w.addObjects(skel_a)
w.addObjects(after_spam_a)
# w.addObjects(after_mi_a)

observable 0x646fca255080(N9anatomist7AVolumeIsEE) could not be removed from observer 0x646fc99e56b8 (N9anatomist8Fusion2DE)
observable 0x646fc905d680(N9anatomist7AVolumeIsEE) could not be removed from observer 0x646fca141b68 (N9anatomist8Fusion2DE)
