In [1]:

import numpy as np
import os
from soma import aims

from sulci.registration.spam import spam_register

import anatomist.api as ana
from soma.qt_gui.qtThread import QtThreadCall
from soma.qt_gui.qt_backend import Qt

a = ana.Anatomist()

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


create qapp
global modules: /casa/host/build/share/anatomist-5.2/python_plugins
home   modules: /casa/home/.anatomist/python_plugins
done
Starting Anatomist.....
config file : /casa/home/.anatomist/config/settings.cfg
PyAnatomist Module present
PythonLauncher::runModules()
loading module meshsplit
loading module palettecontrols
loading module volumepalettes
loading module save_resampled
loading module profilewindow


existing QApplication: 0
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-jc225751'


loading module statsplotwindow
loading module anacontrolmenu
loading module infowindow
loading module foldsplit
loading module simple_controls
loading module histogram
loading module valuesplotwindow
loading module ana_image_math
loading module modelGraphs
loading module paletteViewer
loading module bsa_proba
loading module gradientpalette
loading module selection
loading module gltf_io
all python modules loaded
Anatomist started.


In [2]:

spam_file = '/neurospin/dico/data/deep_folding/current/mask/2mm/L/S.C._left.nii.gz'
skel_f = '/neurospin/dico/data/deep_folding/current/datasets/pclean/binarized_skeletons/L/Lbinarized_skeleton_ammon.nii.gz' 

spam_vol = aims.read(spam_file, dtype='Volume_FLOAT')
spam_vol.np[:] = spam_vol.np/61
skel_data = aims.read(skel_f)
skel_data.np[:] = (skel_data.np > 0).astype(np.int16)

In [3]:
np.unique(spam_vol.np)

array([0.        , 0.01639344, 0.03278688, 0.04918033, 0.06557377,
       0.08196721, 0.09836066, 0.1147541 , 0.13114753, 0.14754099,
       0.16393442, 0.18032786, 0.19672132, 0.21311475, 0.22950819,
       0.24590164, 0.26229507, 0.27868852, 0.29508197, 0.3114754 ,
       0.32786885, 0.3442623 , 0.36065573, 0.37704918, 0.39344263,
       0.40983605, 0.4262295 , 0.44262296, 0.45901638, 0.47540984,
       0.4918033 ], dtype=float32)

In [4]:
np.unique(skel_data)

array([0, 1], dtype=int16)

In [5]:
np.unique(skel_data.np)

array([0, 1], dtype=int16)

In [6]:
spam_vol

In [7]:
out_tr = spam_register(spam_vol,
                       skel_data,
                       do_mask=False,
                       R_angle_var=np.pi / 8,
                       t_var=5.,
                       verbose=False,
                       in_log=False,
                       calibrate_distrib=15.)
aims.write(out_tr, '/tmp/transform.trm')

In [8]:
os.system(f"AimsApplyTransform -i {skel_f} -o /tmp/skel_realigned.nii.gz -m /tmp/transform.trm")

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


loading direct transformations
Output dimensions: 96, 114, 96
Output voxel size: 2, 2, 2 mm
Resampling carto_volume of S16...   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 %


0

In [9]:
spam = a.loadObject(spam_file)
skel = a.loadObject(skel_f)
realigned = a.loadObject("/tmp/skel_realigned.nii.gz")
w = a.createWindow('Sagittal')
w.addObjects(spam)
w.addObjects(skel)
w.addObjects(realigned)

Multitexturing present
function glActiveTexture found.
function glClientActiveTexture found.
function glBlendEquation found.
function glTexImage3D found.
function glMultiTexCoord3f found.
function glBindFramebuffer found.
function glBindRenderbuffer found.
function glFramebufferTexture2D found.
function glGenFramebuffers found.
function glGenRenderbuffers found.
function glFramebufferRenderbuffer found.
function glRenderbufferStorage found.
function glCheckFramebufferStatus found.
function glDeleteRenderbuffers found.
function glDeleteFramebuffers found.
Number of texture units: 4
function glUniform1f found.
function glUniform1i found.
function glUniform4fv found.
function glGetUniformLocation found.
function glMultTransposeMatrixf found.
function glAttachShader found.
function glDetachShader found.
function glCompileShader found.
function glCreateProgram found.
function glCreateShader found.
function glDeleteProgram found.
function glDeleteShader found.
function glGetProgramiv found.


observable 0x566159634f40(N9anatomist7AVolumeIsEE) could not be removed from observer 0x56615a6e9238 (N9anatomist8Fusion2DE)
